name: Poetry CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # checkout repo
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      # install python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      # install poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
      # install dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      # run black
      - name: Run black
        run: poetry run black */*.py
      # generate docs
      - name: Generate docs
        run: poetry run pdoc nsdotpy/session.py -d=google -o=docs/
      # commit & push changes
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # build and publish to pypi
      - name: Build and publish to pypi
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
